{
 "title": "Implementation diagram",
 "panels": [
  {
   "title": "Application Diagram",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "content": "graph LR\n\nA[Kafka Publisher]  --> E(Kafka)\nE  --> B[Spark Streaming App]\nC[gRPC Listener] --> E\nD[HTTP Listener]  --> E\nB-->F(InfluxDb)\nF-->G[Grafana]\nB-->N(Cassandra)\nN-->Z[Zeppelin]\nH[HTTP Publisher]  --HTTP --> D\nK[gRPC Publisher]  --gRPC --> C",
   "targets": [
    {}
   ]
  }
 ]
}
{
 "title": "Raw Data",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "raw_weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "raw_weather",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "raw_weather",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Derived Data",
 "panels": [
  {
   "title": "Daily temperature",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "daily_temp_weather",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "daily_temp_weather",
     "select": [
      [
       { "params": [ "low" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "daily_temp_weather",
     "select": [
      [
       { "params": [ "high" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monthly temperature",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monthly_temp_weather",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monthly_temp_weather",
     "select": [
      [
       { "params": [ "high" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "station" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "monthly_temp_weather",
     "select": [
      [
       { "params": [ "low" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}