{
 "title": "CPU SIGNAL PROCESSING",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Implementation diagram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load Alerting",
   "type": "jdbranham-diagram-panel",
   "description": "CPU load alerting overall implementation",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "content": "graph LR\nA[Data Generator] -- Raw Data topic --> B[Model Serving, based on Tensorflow graph]\nB -- AlertTopic --> E((Alerts, abnormal CPU load))\nA -- Direct write -->  C(InfluxDB)\nC -- Periodic poll -->  D[Machine Learning, based on Intel BigDL]\nD -- Model Update topic --> B\n"
  },
  { "title": "Source Signal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Source data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_data",
     "select": [
      [
       { "params": [ "utilization" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Model Serving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Serving result",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serving_data",
     "select": [
      [
       { "params": [ "served" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "engine" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serving_data",
     "select": [
      [
       { "params": [ "source" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Model Serving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Execution time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "engine" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serving_data",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Individual models results",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serving_model_data",
     "select": [
      [
       { "params": [ "served" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}