{
 "title": "Implementation diagram",
 "panels": [
  {
   "title": "CPU Load Alerting",
   "type": "jdbranham-diagram-panel",
   "description": "CPU load alerting overall implementation",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "content": "graph LR\nA[Data Generator] -- Raw Data topic --> B[Model Serving, based on Tensorflow graph]\nB -- AlertTopic --> E((Alerts, abnormal CPU load))\nA -- Direct write -->  C(InfluxDB)\nC -- Periodic poll -->  D[Machine Learning, based on Intel BigDL]\nD -- Model Update topic --> B\n"
  }
 ]
}
{
 "title": "Source Signal",
 "panels": [
  {
   "title": "Source data",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cpu_data",
     "select": [
      [
       { "params": [ "utilization" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Model Serving",
 "panels": [
  {
   "title": "Serving result",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serving_data",
     "select": [
      [
       { "params": [ "served" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "engine" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serving_data",
     "select": [
      [
       { "params": [ "source" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Model Serving",
 "panels": [
  {
   "title": "Execution time",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "engine" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serving_data",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}
{
 "title": "Model Serving",
 "panels": [
  {
   "title": "Individual models results",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "model" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "serving_model_data",
     "select": [
      [
       { "params": [ "served" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}