apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes deployment of kstream-dsl application. It ingests data from the data file into Kafka topics and does stateful streaming
name: kstreamprocchart
version: 0.1.0
